name: build

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: cargo fmt --all --check
      - run: cargo clippy --all-targets -- -Dwarnings
      - run: cargo test
